### ISSUE TITLE
Find Auth Token

### ISSUE THREAD

**Issue by zcarnefix** [bitfocus/companion-module-vizio-smartcast#13]
I may be missing something obvious, but I am having a hard time finding the auth token to enter into the module. I am unable to create a pair action as the connection status just says NULL. Where should I be looking to get the auth token? Thanks

**Comment by MichaelAllen** [comment]
Because of how these particular TVs work, this module is a bit tricky to setup. But once it is setup, it just works. I have TVs that have been connected for months without issue.

Follow these steps for the initial setup:
1. Setup your instance with the correct IP address. Leave the Auth code blank.
3. Create a button with a `Pair Device` action and push it.
3. A 4 digit code will pop up on the tv for about 30 seconds.
4. Create a button with an `Enter Pin` action and give it the pin that is displayed on the tv. Push that button.
5. Go back and check instance settings and the Auth code should have a value in it now.

Once you have the auth code, you can delete the 2 setup buttons.

**Comment by zcarnefix** [comment]
I think I am getting hung up on just getting the instance up and running. When I enter the IP into the instance and press "Apply Changes", I get this JavaScript error:
<img width="418" alt="Screen Shot 2021-01-27 at 11 10 39 AM" src="https://user-images.githubusercontent.com/76180157/106177130-c16e0d80-615d-11eb-80a6-ea297663e250.png">

 Any idea what might be causing it? Happens on each TV I have tried, all connected over WiFi.

**Comment by MichaelAllen** [comment]
That looks like this bug (#11) that was fixed back in November. What version of Companion are you running? It should be good in the latest official version (2.1.2), as well as any of the newer beta builds.

**Comment by zcarnefix** [comment]
Just updated to newest version of Companion, no more error message.
However, TV's are still not responding to pair actions and will not display
a PIN to enter. Any other suggestions?

**Comment by zcarnefix** [comment]
Tried on a 3rd tv and it appears to be working, so I may have a network
problem with some of the TVs. Thanks for helping me get it sorted out!
